#!/bin/bash

#
# This command creates an up-to-date version of binary wheel included into skill generator
#

TMPL_DIR="$(dirname "$0")"/skill_template/skill-\{\{cookiecutter.skill_name_slug\}\}-\{\{cookiecutter.programming_language\}\}/
OLD_WHEEL=$(ls "$TMPL_DIR"/skill_sdk-*.whl)

python setup.py bdist_wheel --dist-dir="$TMPL_DIR" && rm "$OLD_WHEEL"
